# Generated by Django 3.0.5 on 2020-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingrating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(rating__range=(0, 10)), name='valid_rating'),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(facility__range=(0, 10)), name='valid_facility'),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(staff__range=(0, 10)), name='valid_staff'),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(price__range=(0, 10)), name='valid_price'),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='rating_once'),
        ),
    ]
