# Generated by Django 3.0.5 on 2020-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200423_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrating',
            name='average_ratting',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
