# Generated by Django 3.0.5 on 2020-04-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingrating_average_ratting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingrating',
            old_name='average_ratting',
            new_name='average_rating',
        ),
    ]
