# Generated by Django 3.0.5 on 2020-04-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
