# Generated by Django 3.0.5 on 2020-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200424_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrating',
            name='comment',
            field=models.TextField(default='Service is Very Bad'),
            preserve_default=False,
        ),
    ]
