# Generated by Django 3.0.5 on 2020-04-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingrating_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingrating',
            old_name='comment',
            new_name='review',
        ),
    ]
