# Generated by Django 3.0.5 on 2020-04-23 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200424_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrating',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
