# Generated by Django 3.0.5 on 2020-04-30 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listingbooking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listingrating',
            name='valid_rating',
        ),
        migrations.RemoveConstraint(
            model_name='listingrating',
            name='valid_facility',
        ),
        migrations.AddField(
            model_name='listingbooking',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='listingrating',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='listingrating',
            name='staff',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(rating__range=(0, 5)), name='valid_rating'),
        ),
        migrations.AddConstraint(
            model_name='listingrating',
            constraint=models.CheckConstraint(check=models.Q(facility__range=(0, 5)), name='valid_facility'),
        ),
    ]
