# Generated by Django 3.0.5 on 2020-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200430_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingbooking',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=10, null=True),
        ),
    ]
