# Generated by Django 3.0.5 on 2020-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200503_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': '9. Contact'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-id'], 'verbose_name': 'Listing', 'verbose_name_plural': '2. Listings'},
        ),
        migrations.AlterModelOptions(
            name='listingbooking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': '7. Bookings'},
        ),
        migrations.AlterModelOptions(
            name='listingcomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': '6. Comments'},
        ),
        migrations.AlterModelOptions(
            name='listingextra',
            options={'verbose_name': 'Listing Extra', 'verbose_name_plural': '4. Listing Extras'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'verbose_name': 'Listing Image', 'verbose_name_plural': '3. Listing Images'},
        ),
        migrations.AlterModelOptions(
            name='listingrating',
            options={'verbose_name': 'Listing Rating', 'verbose_name_plural': '5. Listing Rating'},
        ),
        migrations.AlterModelOptions(
            name='sitedetails',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': '8. Site Settings'},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='area',
            new_name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='flat_area',
            field=models.FloatField(default=32),
            preserve_default=False,
        ),
    ]
